name: Handle Texture Pack Uploads

on:
  workflow_dispatch:
    inputs:
      username:
        description: 'Username'
        required: true
        type: string
      password:
        description: 'Password'
        required: true
        type: string
      file_name:
        description: 'Texture Pack File Name'
        required: true
        type: string
      file_content:
        description: 'Base64 Encoded File Content'
        required: true
        type: string

jobs:
  upload_texture_pack:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Decode file content
      run: echo "${{ github.event.inputs.file_content }}" | base64 --decode > texture-pack.zip

    - name: Validate user credentials
      run: |
        USERS_FILE_PATH="path_to_your_repo/users.json"
        USERS_JSON=$(cat $USERS_FILE_PATH)
        USERNAME="${{ github.event.inputs.username }}"
        PASSWORD="${{ github.event.inputs.password }}"
        if ! echo "$USERS_JSON" | jq -e ".\"$USERNAME\" == \"$PASSWORD\""; then
          echo "Invalid credentials" >&2
          exit 1
        fi

    - name: Create new branch and upload texture pack
      run: |
        BRANCH_NAME="new-pack-${{ github.run_id }}"
        git checkout -b "$BRANCH_NAME"
        mkdir -p texture-packs
        mv texture-pack.zip texture-packs/${{ github.event.inputs.file_name }}
        git add texture-packs/${{ github.event.inputs.file_name }}
        git commit -m "Add new texture pack: ${{ github.event.inputs.file_name }}"
        git push origin "$BRANCH_NAME"

    - name: Create pull request
      run: |
        curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
        -d '{"title": "Add new texture pack", "head": "${{ github.run_id }}", "base": "main"}' \
        "https://api.github.com/repos/${{ github.repository }}/pulls"
